inherit_from:
  - ../.rubocop.yml
  - ../conf/.rubocop.yml
  - http://www.example.com/rubocop.yml

inherit_gem:
  my-shared-gem:
    - default.yml
    - strict.yml

Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 59
